neshitje/listing/urls.py
from django.conf.urls import url, patterns, include
from . import views

urlpatterns = [
    url(r'^listing-sample', views.listing, name='listing'),
    url(r'^edit-listing', views.edit_listing, name='edit-listing'),
    url(r'^upload-images', views.image_upload, name='image-upload'),
    url(r'^item/(?P<listing_id>\S+)/$', views.view_listing, name='view-listing'),
    url(r'^view-all-categories', views.category_tree, name='category_tree'),
]

neshitje/main_app/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^contact-us$', views.contact, name='contact'),
]

neshitje/neshitje/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from main_app.views import homepage

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', homepage, name='homepage'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('main_app.urls', namespace="main_app")),
    url(r'^listing/', include('listing.urls', namespace="listing")),
    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^user_details/', include('user_details.urls', namespace="user_details")),
    #url(r'^order/', include('order.urls', namespace="order")),
    url(r'^', include('main_app.urls', namespace = "main_app")),
    # for testing
)

neshitje/search/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^results', views.search_results, name='search_results'),
]

neshitje/user_details/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = [
    url(r'^register', views.register, name='register'),
    url(r'^add-billing-address', views.add_billing, name='add-billing'),
    url(r'^add-postal-address', views.add_postal, name='add-postal'),
    url(r'^my-account', views.account, name='account'),
    url(r'^login', views.login_process, name='login'),
    url(r'^logout', views.logout_process, name='logout'),
    url(r'^logging', views.logging, name='logging'),
    url(r'^delete-postal', views.delete_postal, name='del-postal'),
    url(r'^edit-email', views.edit_email, name='edit-email'),
    url(r'^edit-password', views.edit_password, name='edit-password'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^edit-marketing', views.switch_marketing, name='edit-marketing'),
    url(r'^edit-name', views.edit_name, name='edit-name'),
    url(r'^edit-account-status', views.switch_account_status, name='status-switch'),
    url(r'^edit-phone', views.edit_phone, name='edit-phone'),
    # for password reset
    url(r'^reset-password$','django.contrib.auth.views.password_reset', {'post_reset_redirect' : 'user_details:password_reset_done', 'template_name': 'user_details/reset_password.html', 'email_template_name':'user_details/pwd_reset_email.html'}, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+$)', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : 'user_details:password_reset_complete', 'template_name' : 'user_details/pwd_reset_new.html'}, name='password_reset_confirm'),
    url(r'^reset-done', 'django.contrib.auth.views.password_reset_done', {'template_name' : 'user_details/pwd_reset_done.html'}, name='password_reset_done'),
    url(r'^pwd-reset-complete', 'django.contrib.auth.views.password_reset_done', {'template_name' : 'user_details/pwd_reset_new_done.html'}, name='password_reset_complete'),
]

neshitje/main_app/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status_name = models.CharField(max_length="50")
    status_description = models.CharField(max_length="1000", blank=True, null=True)

    def __str__(self):
        return self.status_name

neshitje/main_app/forms.py
from django import forms

class ContactForm(forms.Form):
    sender = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

neshitje/main_app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.contrib import messages
from .forms import ContactForm

def homepage(request):
    #messages.info(request, "This is a test message for success!")
    return render(request, 'main_app/homepage.html', {})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            print "message sent"
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            recipients = ['info@neshitje.com']
            send_mail(subject, message, sender, recipients)

            messages.success(request, "Many thanks for your email. Your enquiry has been sent.")
        else:
            messages.success(request, "Please not that there was an error. Your message has not been sent.")
            return render(request, 'main_app/contact_us.html', {'form':form})


    form = ContactForm()
    return render(request, 'main_app/contact_us.html', {'form':form})

neshitje/main_app/templates/main_app/base.html
{% load staticfiles %}
<html>
<head>
  {% block header %}
  <title>N&#235; Shitje</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <!-- reCaptcha JavaScript -->
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <!-- Script for EU cookie directove -->
  <script src="{% static "js/jquery.cookiesdirective.js" %}"> </script>
  <!-- own JavaSctipt library -->
  <script src="{% static "js/neshitje.js" %}"> </script>


  <link rel="stylesheet" href="{% static "css/styles.css" %}" />

  {% block additionalcss %}
  {% endblock %}

  {% endblock %}
</head>

<body>
  {# Include this for Google Tagmanager #}
  {% include "main_app/tagmanager.html" %}

  {% block navigation %}
    <nav class="navbar navbar-fixed-top navbar-default">

    {% include "main_app/top_navigation.html" %}
    {% block subnav %}
    {% endblock %}

    </nav>
    {% block extrapadding %}
    {% endblock %}

  {% endblock %}

  {% block messages %}
    {% if messages %}
      <div class="container-fluid" id="alert-message">
        <div class="col-sm-6 col-sm-offset-3">
          {% for message in messages %}
            {% if message.tags == "success" %} <p class="alert alert-success"> {{ message }}</p> {% endif %}
            {% if message.tags == "info" %} <p class="alert alert-info"> {{ message }}</p> {% endif %}
            {% if message.tags == "warning" %} <p class="alert alert-warning"> {{ message }}</p> {% endif %}
            {% if message.tags == "error" %} <p class="alert alert-danger"> {{ message }}</p> {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
  {% endblock %}

  <!-- This part should really be removed -->
  <div style="min-height: 520px;">
  {% block content %}


  {% endblock %}
  <!-- This part should really be removed -->
  </div>

  {% block footer %}
    <div class="container-fluid" id="footer">
      <div>
        Footer Links
      </div>
    </div>
  {% endblock %}

  <script type="text/javascript">
      $(document).ready(function() {
          $.cookiesDirective({
              privacyPolicyUri: 'my-privacy-policy.html',
              position: 'bottom',
              explicitConsent: false,
              duration: 30,
              linkColor: '#129793',
              backgroundOpacity: 99,
              backgroundColor: '#cccccc',
              fontColor: '#535353'
          });
      });
  </script>
</body>

neshitje/main_app/templates/main_app/contact_us.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}
{% block content %}

  <div class="container-fluid">
    <h1>Get in touch...</h1>
    <div id="contact-map">
      <div class="col-md-4" id="map-intro">
        <h2>Where we are:</h2>
        <div id="map-lore">
          <span>In the ideallic outskirts of London, in beautiful Hillingdon, Conveniently located within 20 minutes to Heathrow and 40 minutes into central London. Just where the A40 meets the M40 and M25.</span>
        </div>
      </div>
      <div class="col-md-8" id="map-view">

        <img title="Our Office Location" src="http://maps.googleapis.com/maps/api/staticmap?center=London&key=AIzaSyBx-Q-iEbDA7oUipQcElWLAu_NATEV3HXg&size=750x350&zoom=10&style=saturation:-100|lightness:-10|gamma:0.75&style=feature:landscape|element:geometry|saturation:-100&markers=color:0x129793|label:N|51.5357817,-0.4527881&style=feature:road.highway|element:labels.icon|visibility:off" />

      </div>
    </div>
    <div class="col-md-12">
      <hr>
    </div>
    <div id="contactly">
      <div class="col-md-offset-2 col-md-4" >
        <h2>Address:</h2>
        <div id="address">
          Ne Shitje<br/>
          34 The Larches<br/>
          UB10 0DJ<br/>
          London, UK<br/>
          t) +44 1895 460 705<br/>
          e) <a href="mailto:info@neshitje.com?subject=1359|" title="send us a letter">info @ neshitje . com</a>
        </div>
      </div>
      <hr>
      <div class="col-md-offset-1 col-md-5" >
        <h2>Contact Form:</h2>
        <div id="address">
          <form method="post" action="{% url 'main_app:contact' %}" class="form-horizontal" role="form" >
            {% csrf_token %}

            {% for field in form %}
            <div class="form-group">
                {{ field.errors.as_text }}
              <label class="control-label col-sm-2" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
              <div class="col-sm-10" id="message-small">
                {% render_field field class+="form-control" rows=7 placeholder="required" %}
              </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <div class="text-right" style="padding-right: 15px;"><button type="submit" class="btn btn-success glyphicon glyphicon-envelope " name="send" value="submit"> Send</button></div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

neshitje/main_app/templates/main_app/content_template.html
{% extends "main_app/base.html" %}

{% block content %}

  <div class="container-fluid">
    Hello
  </div>

{% endblock content %}

neshitje/main_app/templates/main_app/save_form.html
{% load widget_tweaks %}
{{ form.non_field_errors }}
<form onsubmit="return validateForm()" action="{% url obj %}" class="form-horizontal" role="form" method="post">
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group">
        {{ field.errors.as_text }}
      <label class="control-label col-sm-3" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
      <div class="col-sm-8">
        {% render_field field class+="form-control" %}
      </div>
    </div>
  {% endfor %}

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-8">
      <div class="left-right">
        <button id="save-button" type="submit" class="btn btn-success" name="save" value="submit">Save</button>
      </div>
    </div>
  </div>
</form>

neshitje/main_app/templates/main_app/tagmanager.html
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NGS2MN"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NGS2MN');</script>
<!-- End Google Tag Manager -->

neshitje/main_app/templates/main_app/top_navigation.html
  <div id="logo-header" class="container-fluid"><a href="/" title="N&#235; Shitje Homepage">N&#235; Shitje</a></div>
  <div id="tagline" class="container-fluid">The place to buy and sell</div>

  <div class="container-fluid">
  <div id="small-logo-header" class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" id="navbar-brand" href="/">N&#235; Shitje</a>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <!--<li class="active"><a href="#">Home</a></li>-->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Departments<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Properties</a></li>
          <li><a href="#">Cars & Vehicles</a></li>
          <li><a href="#">Electronics</a></li>
          <li><a href="#">Cameras</a></li>
          <li><a href="#">Home & Garden</a></li>
          <li><a href="#">Furniture</a></li>
          <li><a href="#">Clothing</a></li>
        </ul>
      </li>
      <li><a href="#">About Ne Shitje</a></li>
      <li><a href="{% url 'main_app:contact' %}">Contact Us</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Cheat Section<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'user_details:account' %}">User Account</a></li>
          <li><a href="{% url 'user_details:password_reset' %}">Reset Password</a></li>
          <li><a href="{% url 'listing:listing' %}">Product Page</a></li>
          <li><a href="{% url 'search:search' %}">Search Page</a></li>
          <li><a href="{% url 'search:search_results' %}">Search Results Page</a></li>
          <li><a href="#">Category Page</a></li>
          <li><a href="{% url 'listing:edit-listing' %}">List Item Page</a></li>
          <li><a href="{% url 'listing:image-upload' %}">Upload and image</a></li>
          <li><a href="#">Manage Items</a></li>
          <li><a href="#">Purchases</a></li>
          <li><a href="#">Cart</a></li>
          <li><a href="#">Checkout</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'main_app:homepage' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Basket</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'user_details:account' %}"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
        <li><a href="{% url 'user_details:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      {% else %}
        <li><a href="{% url 'user_details:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#" data-toggle="modal" data-target="#signupModal"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>
  </div>
</div>


<!-- Modal -->
<div class="modal fade " id="signupModal" role="dialog" > <!-- Optional: data-backdrop="false" -->
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign In</h4>
      </div>
      <div class="modal-body">
        <form role="form" method="post" action="{% url 'user_details:login' %}"> {% csrf_token %}
          <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" id="ppasswordwd" placeholder="Enter password" name="password" required>
          </div>
          <div class="checkbox">
            <label><input type="checkbox"> Remember me</label>
          </div>
        <div class="left-right"><button type="submit" class="btn btn-success" value="login" >Login</button></div>
        </form>
        <div class="text-right"><button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button></div>
      </div>
      <div class="modal-footer">
        <span>Or <a href="{% url 'user_details:register' %}" >create an account</a> or use this form to <a href="{% url 'user_details:password_reset' %}">reset your password</a>.</span>
      </div>
    </div>
  </div>
</div>