neshitje/neshitje/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from main_app.views import homepage

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', homepage, name='homepage'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('main_app.urls', namespace="main_app")),
    url(r'^listing/', include('listing.urls', namespace="listing")),
    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^user_details/', include('user_details.urls', namespace="user_details")),
    #url(r'^order/', include('order.urls', namespace="order")),
    url(r'^', include('main_app.urls', namespace = "main_app")),
    # for testing
)

neshitje/search/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^results', views.search_results, name='search_results'),
]

neshitje/user_details/urls.py
from django.conf.urls import url, patterns, include

from . import views

urlpatterns = [
    url(r'^register', views.register, name='register'),
    url(r'^add-billing-address', views.add_billing, name='add-billing'),
    url(r'^add-postal-address', views.add_postal, name='add-postal'),
    url(r'^my-account', views.account, name='account'),
    url(r'^login', views.login_process, name='login'),
    url(r'^logout', views.logout_process, name='logout'),
    url(r'^logging', views.logging, name='logging'),
    url(r'^delete-postal', views.delete_postal, name='del-postal'),
    url(r'^edit-email', views.edit_email, name='edit-email'),
    url(r'^edit-password', views.edit_password, name='edit-password'),
    url(r'^profile', views.profile, name='profile'),
    url(r'^edit-marketing', views.switch_marketing, name='edit-marketing'),
    url(r'^edit-name', views.edit_name, name='edit-name'),
    url(r'^edit-account-status', views.switch_account_status, name='status-switch'),
    url(r'^edit-phone', views.edit_phone, name='edit-phone'),
    # for password reset
    url(r'^reset-password$','django.contrib.auth.views.password_reset', {'post_reset_redirect' : 'user_details:password_reset_done', 'template_name': 'user_details/reset_password.html', 'email_template_name':'user_details/pwd_reset_email.html'}, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+$)', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : 'user_details:password_reset_complete', 'template_name' : 'user_details/pwd_reset_new.html'}, name='password_reset_confirm'),
    url(r'^reset-done', 'django.contrib.auth.views.password_reset_done', {'template_name' : 'user_details/pwd_reset_done.html'}, name='password_reset_done'),
    url(r'^pwd-reset-complete', 'django.contrib.auth.views.password_reset_done', {'template_name' : 'user_details/pwd_reset_new_done.html'}, name='password_reset_complete'),
]

neshitje/user_details/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from main_app.models import Status

# Create your models here.

class UserDetail(models.Model):
    date_created = models.DateTimeField("Date time created", auto_now_add=True, auto_now=False)
    status = models.ForeignKey(Status, default=1)
    status_changed = models.DateTimeField("Date time updated", auto_now_add=False, auto_now=True)
    phone_number = models.CharField(max_length=16, blank=True, null=True)
    gender = models.CharField(max_length=50, blank=True, null=True)
    user = models.OneToOneField(User)
    marketing_optin = models.BooleanField(default=True)

    def __str__(self):
        return self.user


class UserBilling(models.Model):
    date_created = models.DateTimeField("Date time created", auto_now_add=True, auto_now=False)
    is_active = models.BooleanField(default=True)
    address_line_1 = models.CharField(max_length=55, blank=True, null=True)
    address_line_2 = models.CharField(max_length=55, blank=True, null=True)
    address_line_3 = models.CharField(max_length=55, blank=True, null=True)
    city = models.CharField(max_length=55, blank=True, null=True)
    post_code = models.CharField(max_length=10, blank=True, null=True)
    user = models.ForeignKey(User)
    status_changed = models.DateTimeField("Date time updated", auto_now_add=False, auto_now=True)
    status = models.ForeignKey(Status, default=1)

    def __str__(self):
        return str(self.address_line_1)


class UserShipping(models.Model):
    address_line_1 = models.CharField(max_length=55, blank=True, null=True)
    address_line_2 = models.CharField(max_length=55, blank=True, null=True)
    address_line_3 = models.CharField(max_length=55, blank=True, null=True)
    city = models.CharField(max_length=55, blank=True, null=True)
    post_code = models.CharField(max_length=10, blank=True, null=True)
    address_nick = models.CharField(max_length=55, blank=True, null=True)
    date_created = models.DateTimeField("Date time created", auto_now_add=True, auto_now=False)
    is_active = models.BooleanField(default = True)
    user = models.ForeignKey(User)
    status = models.ForeignKey(Status, default=1)
    status_changed = models.DateTimeField("Date time updated", auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.address_nick

# Other infos

neshitje/user_details/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.contrib import auth, messages
from django.core.context_processors import csrf
from .forms import UserRegForm, BillingForm, PostalForm, LoginForm, ChangeEmailForm, ChangePasswordForm, ChangeNameForm, CloseAccountForm, ChangeEmailOptinForm, ChangePhoneForm
from .models import UserBilling, UserShipping
from main_app.models import Status

import main_app.recaptcha_simple

### Universal functions ###

### Captcha Section, leave only one of them. If former, you don't need to install recaptcha-client ###

### From here on is views: ###
def add_billing(request):
    if request.user.is_authenticated():
        user_id = request.user

        if request.method == 'POST':
            form = BillingForm(request.POST)
            if form.is_valid():
                try:
                    billing = UserBilling.objects.get(user_id=user_id, status=1)
                    if billing is not None:
                        billing.status = Status.objects.get(pk=3)
                        billing.save()

                except:
                    print "this is the first billing address"

                form.save(user_id)

                if request.POST.get('save') == 'submit':
                    messages.success(request, "Billing address created!")
                    response = redirect('user_details:account')

                elif request.POST.get('add_shipping') == 'submit':
                    messages.success(request, "Billing address created!")
                    response = redirect('user_details:add-shipping')

                else:
                    response = redirect('user_details:account')

                return response

            else:
                messages.warning(request, "Your billing address couldn't be updated")
                form = BillingForm(instance=billing)
                return render(request, 'user_details/add_billing_address.html', {'form' : form})

        else:
            billing = None
            try:
                billing = UserBilling.objects.get(user_id=user_id, status=1)
            except:
                #messages.info(request, "This would be your first billing address")
                print "this is the first billing address"

            form = BillingForm(instance=billing)
            return render(request, 'user_details/add_billing_address.html', {'form': form})

    else:
        request.session['direct_url'] = 'user_details:add-billing'
        response = redirect('user_details:logging')
        return response


def add_postal(request):
    if request.user.is_authenticated():
        user_id = request.user
        postals = UserShipping.objects.filter(user_id=user_id, status=1)

        if request.method == 'POST':
            form = PostalForm(request.POST)
            if form.is_valid():
                print "Postal success"
                form.save(user_id)
                messages.success(request, "Postal address added!")
                response = redirect('user_details:account')
                return response

            return render(request, 'user_details/add_postal_address.html', {'form' : form, 'postals':postals})
        else:
            form = PostalForm()
            return render(request, 'user_details/add_postal_address.html', {'form': form, 'postals':postals})

    else:
        request.session['direct_url'] = 'user_details:add-postal'
        response = redirect('user_details:logging')
        return response


def logging(request):

    if not request.session.get('direct_url', False):
        messages.warning(request, "We are sorry, we forgot where you want to go, so we sent you here.")
        url = "user_details:register"
    else:
        url = request.session.get('direct_url')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid:
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')

            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                messages.success(request, "Thank you for logging in")
                response = redirect(url)
                return response
            else:
                messages.warning(request, "There was an error logging you in.")
                response = redirect('user_details:logging')
                return response
        else:
            messages.warning(request, "There was an error trying to log you in")
            return render(request, 'user_details/logging.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'user_details/logging.html', {'form': form})


def login_process(request):

    referrer = None
    try:
        referrer = request.META['HTTP_REFERER']
    except KeyError:
        referrer = "user_details:register"

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        messages.success(request, "Hello " + user.first_name + ", you are now logged in.")
        response = redirect(referrer)
        return response
    else:
        response = redirect(referrer)
        messages.error(request, "User not found!")
        return response


def logout_process(request):

    referrer = None
    try:
        referrer = request.META['HTTP_REFERER']
    except KeyError:
        referrer = 'main_app:homepage'

    if request.session.get('delete'):
        delete = request.session.get('delete')
        user = request.user
        if user.id == delete:
            user.is_active = False
            user.userdetail.status_id = 3
            user.userdetail.save()
            user.save()
            messages.success(request, "Your account was successfully deactivated.")
    auth.logout(request)
    messages.success(request, "Logged out!")
    return redirect(referrer)


def register(request):
    if request.method == 'POST':
        #print request
        response = main_app.recaptcha_simple.submit(request.POST.get('g-recaptcha-response'), request.META['REMOTE_ADDR'])
        if response.is_valid:
            form = UserRegForm(request.POST)
            if form.is_valid():
                print "User reg form success"
                form.save()
                messages.success(request, "Account created!")
                if request.POST.get('details') == 'submit':
                    response = redirect('user_details:add-billing')
                else:
                    response = redirect('user_details:account')
                return response
            else:
                return render(request, 'user_details/register_base.html', {'form' : form})
        else:
            # return the form
            messages.warning(request, "The re-captcha was most likely wrong!")
            response = redirect('user_details:register')
            response['Location'] += '?fail=recaptcha'
            return response

    form = UserRegForm()
    return render(request, 'user_details/register_base.html', {'form' : form})

def delete_postal(request):
    if request.user.is_authenticated():
        if request.method == 'GET':
            postal_id = request.GET.get('postal_id', None)
            post_add = UserShipping.objects.get(id=postal_id)
            post_add.status = 3
            post_add.save();
            messages.success(request, "Postal address deleted!")
        return render(request, 'user_details/account.html', {})
    else:
        request.session['direct_url'] = 'user_details:del-postal'
        response = redirect('user_details:logging')
        return response

def account(request):
    if request.user.is_authenticated():
        return render(request, 'user_details/account.html', {})
    else:
        request.session['direct_url'] = 'user_details:account'
        response = redirect('user_details:logging')
        return response


## This one is mainly to try around in.
def edit_phone(request):
    if request.user.is_authenticated():

        if request.method == 'POST':
            form = UserRegForm(request.POST)
            if form.is_valid():
                print "User reg form success"
                form.save()
                messages.success(request, "Phone number updated.")
                response = redirect('user_details:account')
                return response
            else:
                messages.warning(request, "Phone number not updated.")
                return render(request, 'user_details/edit_phone.html', {'form' : form})
        return render(request, 'user_details/edit_phone.html', {'form' : form})

    else:
        request.session['direct_url'] = 'user_details:edit-phone'
        response = redirect('user_details:logging')
        return response

def edit_email(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            user_id = request.user
            form = ChangeEmailForm(request.POST)
            if form.is_valid():
                password = request.POST.get('password', '')
                email = request.POST.get('email', '')
                user = auth.authenticate(username=user_id.username, password=password)
                if user is not None:
                    auth.login(request, user)
                    user.email = email
                    user.save()
                    messages.success(request, "Email address updated")
                    response = redirect('user_details:account')
                    return response
                else:
                    messages.warning(request, "Email address not updated")
                    response = redirect('user_details:edit-email')
                    return response
            else:

neshitje/user_details/templates/user_details/add_billing_address.html
{% extends "user_details/account.html" %}
{% load widget_tweaks %}
{% block account_content %}

<script type="text/javascript">
  function validateForm() {
    var add01 = document.getElementById('id_address_line_1');
    var add02 = document.getElementById('id_address_line_2');
    var add03 = document.getElementById('id_address_line_3');
    var pc = document.getElementById('id_post_code');
    var cit = document.getElementById('id_city');

    if (add01.value.length < 6) {
      alert("Address Line 1 cannot be empty and must be at least 6 characters");
      return false;
    }

    if (pc.value.length < 2) {
      alert("We need the post code.");
      return false;
    }

    if (city.value.length < 4) {
      alert("Please enter a city with more than 3 characters");
      return false;
    }

		return true;
  }
</script>

<h1>Your billing address</h1>
<div class="container">
  <form name="billing_form" class="form-horizontal" role="form" method="post" onsubmit="return validateForm();"  action="{% url 'user_details:add-billing' %}">
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
          {{ field.errors.as_text }}
        <label class="control-label col-sm-2" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
        <div class="col-sm-10">
          {% render_field field class+="form-control" %}
        </div>
      </div>
    {% endfor %}

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="left-right"><button type="submit" class="btn btn-success" name="save" value="submit">Save</button></div>
      </div>
    </div>
  </form>
</div>
{% endblock account_content %}

{% block footer %}
{% endblock footer %}

neshitje/user_details/templates/user_details/add_postal_address.html
{% extends "user_details/account.html" %}
{% load widget_tweaks %}
{% block account_content %}

<script type="text/javascript">
  function ValidateAccount() {
    var add01 = document.getElementById('id_address_line_1');
    var add02 = document.getElementById('id_address_line_2');
    var add03 = document.getElementById('id_address_line_3');
    var pc = document.getElementById('id_post_code');
    var cit = document.getElementById('id_city');
    var nick = document.getElementById('id_address_nick');

    if (add01.value.length < 6) {
      alert("Address Line 1 cannot be empty and must be at least 6 characters");
      return false;
    }

    if (pc.value.length < 2) {
      alert("We need the post code.");
      return false;
    }

    if (city.value.length < 4) {
      alert("Please enter a city with more than 3 characters");
      return false;
    }

    if (nick.value.length < 1) {
      alert("Address must have a nick to be saved");
      return false;
    }

		return true;
  }
</script>


<h1>Postal Addresses</h1>
<div class="container-fluid">
</div>

{% if postals %}
  <div class="container">
    <h2>Current registered addresses</h2>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Address Nick</th>
          <th>Address Line 1</th>
          <th>Address Line 2</th>
          <th>Address Line 3</th>
          <th>City</th>
          <th>Post Code</th>
          <th>delete?</th>
        </tr>
      </thead>
      <tbody>
      {% for line in postals %}
          <tr>
            <td>{{ line.address_nick }}</td>
            <td>{{ line.address_line_1 }}</td>
            <td>{{ line.address_line_2 }}</td>
            <td>{{ line.address_line_3 }}</td>
            <td>{{ line.city }}</td>
            <td>{{ line.post_code }}</td>
            <td><a href="{% url 'user_details:del-postal' %}?postal_id={{ line.id }}" title="delete">{{ line.post_code }}</a></td>
          </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %}


<div class="container">
  <h2>Add Delivery Address</h2>
  <form name="billing_form" class="form-horizontal" role="form" method="post" onsubmit="return ValidateAccount();" action="{% url 'user_details:add-postal' %}">
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
          {{ field.errors.as_text }}
        <label class="control-label col-sm-2" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
        <div class="col-sm-10">
          {% render_field field class+="form-control" %}
        </div>
      </div>
    {% endfor %}

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="left-right"><button type="submit" class="btn btn-success" name="save"  value="save">Save</button></div>
      </div>
    </div>
  </form>
</div>
{% endblock account_content %}

{% block footer %}
{% endblock footer %}

neshitje/user_details/templates/user_details/edit_email.html
{% extends "user_details/profile.html" %}

{% block profile_action %}
<div class="panel panel-default" id="profile-panel-box">
  <div class="panel-heading">Change Email Address</div>
    <div class="panel-body">
      {% include "main_app/save_form.html"%}
    </div>
</div>
{% endblock profile_action %}

neshitje/user_details/templates/user_details/edit_marketing.html
{% extends "user_details/profile.html" %}
{% load widget_tweaks %}

{% block profile_action %}
<div class="panel panel-default" id="profile-panel-box">
  <div class="panel-heading">Edit your marketing preferences</div>
    <div class="panel-body">
      <p>
        Stop receiving marketing emails. This includes wishlist and updates about listings. You will still receive emails that are important to your account and to compliance with our terms and conditions.
      </p>

      {{ form.non_field_errors }}
      <form name="marketing-form" class="form-horizontal" role="form" method="post" onsubmit="return validateForm();"  action="{% url 'user_details:edit-marketing' %}">
        {% csrf_token %}
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2" style="text-align: right; padding-top: 7px;">
              {% if optin %}
                {% render_field form.optin|attr:"checked" %}
              {% else %}
                {% render_field form.optin %}
              {% endif %}
            </div>
            <label class="control-label col-sm-5" for="email-opt-in"> Ticked to receive marketing emails.</label>
          </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-9" style="padding-right:50px">
            <button type="submit" class="btn btn-block btn-primary" name="delete"  value="save">Update email preferences</button>
          </div>
        </div>
      </form>
    </div>
</div>
{% endblock profile_action %}

neshitje/user_details/templates/user_details/edit_name.html
{% extends "user_details/profile.html" %}

{% block profile_action %}
<div class="panel panel-default" id="profile-panel-box">
  <div class="panel-heading">Change your name</div>
    <div class="panel-body">
      {% include "main_app/save_form.html"%}
    </div>
</div>
{% endblock profile_action %}

neshitje/user_details/templates/user_details/edit_password.html
{% extends "user_details/profile.html" %}

{% block profile_action %}
<div class="panel panel-default" id="profile-panel-box">
  <div class="panel-heading">Change Password</div>
    <div class="panel-body">
      {% include "main_app/save_form.html"%}
    </div>
</div>
{% endblock profile_action %}

neshitje/user_details/templates/user_details/edit_phone.html
{% extends "user_details/profile.html" %}

{% block profile_action %}
<div class="panel panel-default" id="profile-panel-box">
  <div class="panel-heading">Change your phone number</div>
    <div class="panel-body">
      {% include "main_app/save_form.html"%}
    </div>
</div>
{% endblock profile_action %}

neshitje/user_details/templates/user_details/logging.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
  <h1>Please login first</h1>
  <form name="login-form" class="form-horizontal" role="form" method="post" action="{% url 'user_details:logging' %}">
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
          {{ field.errors.as_text }}
        <label class="control-label col-sm-2" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
        <div class="col-sm-10">
          {% render_field field class+="form-control" %}
        </div>
      </div>
    {% endfor %}

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="text-right"><button type="submit" class="btn btn-success" name="save" value="submit">Login</button></div>
      </div>
    </div>
  </form>
</div>

{% endblock content %}

neshitje/user_details/templates/user_details/pwd_reset_done.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
  <h1>Reset your password</h1>
  <p>We've emailed you instructions for setting your password. You should be receiving them shortly.<br/>
    If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>

{% endblock content %}

neshitje/user_details/templates/user_details/pwd_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}/user_details/reset/{{uid}}/{{token}}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

neshitje/user_details/templates/user_details/pwd_reset_new.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}
<div class="container">
  <h1>Reset your password</h1>

  {% if validlink %}
  <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

  {{ form.non_field_errors }}

  <form onsubmit="return validateForm()" class="form-horizontal" role="form" method="post" action="">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.errors.as_text }}
      <label class="control-label col-sm-3" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
      <div class="col-sm-8">
        {% render_field field class+="form-control" placeholder="Password" %}
      </div>
    </div>
    {% endfor %}

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8">
        <div class="left-right">
          <button id="save-button" type="submit" class="btn btn-primary" name="save" value="submit">Change my password</button>
        </div>
      </div>
    </div>
  </form>


  {% else %}

  <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

  {% endif %}

</div>
{% endblock %}

neshitje/user_details/templates/user_details/pwd_reset_new_done.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
  <h1>Reset your password</h1>
  <p>Password reset complete. You should be able to log on with your username and password.</p>
</div>


{% endblock content %}

neshitje/user_details/templates/user_details/register_base.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}
{% block content %}

<script type="text/javascript">
  function noWhiteSpace(str) {
    return /^\S{5,}$/.test(str);
  }

  function validateEmail(email) {
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
  }

  function checkPassword(str) {
   // at least one number, one lowercase and one uppercase letter
   // at least six characters
   var re = /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/;
   return re.test(str);
 }

  function validateForm() {
    var emailID = document.getElementById('id_email');
    var username = document.getElementById('id_username');
    var firstname = document.getElementById('id_first_name');
    var password = document.getElementById('id_password1');
    var conf_pass = document.getElementById('id_password2');

    if (firstname.value.length < 2) {
      alert("First name cannot be empty and must be at least 2 characters");
      return false;
    }

    if (!noWhiteSpace(username.value)) {
      alert("Username can not be empty, must be 5 characters long and must have no whitespace. Special characters are also not okay.");
      return false;
    }

    if (!checkPassword(password.value)) {
      alert("A password needs to have 1 UpperCase letter, 1 lower case letter, at least 1 number and be 6 characters long.");
      return false;
    }
    if (password.value != conf_pass.value) {
      alert("Password and Confirmation must be the same");
      return false;
    }

    if (!validateEmail(emailID.value)) {
        alert("Not a valid email")
        return false;
    }

    return true;

  }
</script>

  <div class="container">

    <h1>Register Form</h1>
    {{ form.non_field_errors }}
    <form onsubmit="return validateForm()" action="{% url 'user_details:register' %}" class="form-horizontal" role="form" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group">
            {{ field.errors.as_text }}
          <label class="control-label col-sm-2" for="{{ field.id_for_label }}"> {{ field.label }}: </label>
          <div class="col-sm-10">
            {% render_field field class+="form-control" %}
          </div>
        </div>
      {% endfor %}

      <div>
        <div class="g-recaptcha col-sm-offset-5 col-sm-7" style="padding-bottom: 10px;" data-sitekey="6LduyQwTAAAAANHdf2AKPWMk0fylju7dBwbdcrIm"></div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="left-right">
            <button type="submit" class="btn btn-success" name="save" value="submit">
              <span class="glyphicon glyphicon-user"></span> Create Account
            </button>
          </div>
            <!--
            <div class="text-right">
              <button type="submit" class="btn btn-success" name="details" value="submit">
                <span class="glyphicon glyphicon-chevron-right"></span> Further Details
              </button>
            </div>
          -->
          </div>
        </div>
    </form>
    <hr />
    <div class="col-sm-offset-2 col-sm-10">or: <button type="button" class="btn btn-default glyphicon glyphicon-log-in" data-toggle="modal" data-target="#signupModal" > Login</button></div>
  </div>

{% endblock content %}

{% block footer %}
{% endblock footer %}

neshitje/user_details/templates/user_details/reset_password.html
{% extends "main_app/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
  <h1>Reset your password</h1>
  <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

  {{ form.non_field_errors }}

  <form onsubmit="return validateForm()" class="form-inline" role="form" method="post" action="{% url 'user_details:password_reset' %}">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
          {{ field.errors.as_text }}
        <label class="control-label" for="{{ field.id_for_label }}">Email Address: </label>
          {% render_field field class+="form-control" placeholder="your@email.com" %}
      </div>
    {% endfor %}

    <button id="save-button" type="submit" class="btn btn-primary" name="save" value="submit">Reset my password</button>

  </form>


</div>

{% endblock content %}